server:
  # 服务器访问端口
  port: 8080
  # 访问的基础路径
  context-path: /
spring:
  datasource:
    url: jdbc:mysql://192.168.80.138:3306/employees
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    # 集群配置
    cluster:
      nodes: 
        - 192.168.80.138:7000
        - 192.168.80.138:7001
        - 192.168.80.138:7002
        - 192.168.80.138:7003
        - 192.168.80.138:7004
        - 192.168.80.138:7005
    pool:
      min-idle: 8
      max-wait: 1000
      max-idle: 0
      max-active: 8
    # 单机配置
    # port: 6379
    # host: 192.168.80.138
    
    
    