feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true
  okhttp:
    enabled: false
ribbon:  eager-load:    enabled: true
    clients: feign-api-url
  http:
    client:
      enabled: true
  okhttp:
    enabled: false
feign-api-url:
  ribbon:
    listOfServers: 192.168.80.138:8081,192.168.80.131:8081
         # 策略
    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.availability    ConnectTimeout: 500    ReadTimeout: 2000
         # 以下配置后，会发生单独Server不好使，直接fallback触发并且重试的生效
         # 所有情况都重试    # OkToRetryOnAllOperations: false
         # 当前实例全部失败后可以换1个实例再重试    # MaxAutoRetries: 1
         # 在当前实例只重试2次    # MaxAutoRetriesNextServer: 2