ribbon:
  http:
    client:
      enabled: true
feign:
  hystrix:
    enabled: true 
hystrix:
  propagate:
    request-attribute:
      enabled: true
  command:
    #全局默认配置
    default:
      #线程隔离相关
      execution:
        timeout:
          #是否给方法执行设置超时时间，默认为true。一般我们不要改。
          enabled: true
        isolation:
          thread:
            #方式执行的超时时间，默认为1000毫秒，在实际场景中需要根据情况设置
            # 其设置时间必须大于Ribbon的重试时间，否则会发生重试与Fallback同时触发的情况
            timeoutInMilliseconds: 10000
            #发生超时时是否中断方法的执行，默认值为true。不要改。
            interruptOnTimeout: true
            #是否在方法执行被取消时中断方法，默认值为false。没有实际意义，默认就好！
            interruptOnCancel: false
feign-api-url:
  ribbon:
    listOfServers: 192.168.80.138:8081,192.168.80.131:8081
    #说明：同一台实例的最大自动重试次数，默认为1次，不包括首次
    MaxAutoRetries: 1
    #说明：要重试的下一个实例的最大数量，默认为1，不包括第一次被调用的实例
    MaxAutoRetriesNextServer: 1
    #说明：是否所有的操作都重试，默认为true
    OkToRetryOnAllOperations: true
    #说明：使用Apache HttpClient连接超时时间，单位为毫秒
    ConnectTimeout: 1000
    #说明：使用Apache HttpClient读取的超时时间，单位为毫秒
    ReadTimeout: 2000
